spring:
  profiles:
    active: dev
    application:
      name: showcase
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: example
---
spring:
  profiles: dev

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8080
